name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload release assets
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: cursor-mcp-subagents-linux-x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact: cursor-mcp-subagents-linux-aarch64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: cursor-mcp-subagents-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: cursor-mcp-subagents-macos-aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: cursor-mcp-subagents-windows-x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            cargo install cross --git https://github.com/cross-rs/cross --force
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Prepare artifact
        shell: bash
        run: |
          BIN_NAME=cursor-mcp-subagents
          EXT=""
          if [[ "${{ matrix.target }}" == *windows* ]]; then EXT=".exe"; fi
          SRC="target/${{ matrix.target }}/release/${BIN_NAME}${EXT}"
          mkdir -p dist
          OUT="dist/${{ matrix.artifact }}${EXT}"
          cp "$SRC" "$OUT"

      - name: Generate SHA256 checksums
        shell: bash
        run: |
          for f in dist/*; do
            if command -v sha256sum >/dev/null 2>&1; then
              sha256sum "$f" > "$f.sha256"
            elif command -v shasum >/dev/null 2>&1; then
              shasum -a 256 "$f" > "$f.sha256"
            else
              if [[ "$RUNNER_OS" == "Windows" ]]; then
                # certutil prints the hash on the second line
                HASH=$(certutil -hashfile "$f" SHA256 | sed -n '2p' | tr -d '\r')
                BASENAME=$(basename "$f")
                echo "$HASH  $BASENAME" > "$f.sha256"
              else
                echo "No checksum tool found" && exit 1
              fi
            fi
          done

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
